import type { Metadata } from "next";
import { AppSidebar } from "@/components/navbar/app-sidebar";
import {
  SidebarInset,
  SidebarProvider,
  SidebarTrigger,
} from "@/components/ui/sidebar";
import "./globals.css";
import { SearchForm } from "@/components/search-form";
import { NowPlaying } from "@/components/now-playing";
import { AlertDialogProvider } from "@/components/provider/alert-provider";
import { LoadingProvider } from "@/components/provider/loading-provider";

export const metadata: Metadata = {
  title: "Tongla Music App",
  description: "Generated by tongla_dev",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <AlertDialogProvider>
          <SidebarProvider>
            <LoadingProvider>
              <AppSidebar />
              <SidebarInset>
                <header className="flex h-16 shrink-0 items-center gap-2 transition-[width,height] ease-linear group-has-[[data-collapsible=icon]]/sidebar-wrapper:h-12">
                  <div className="flex items-center gap-2 px-4">
                    <SidebarTrigger className="-ml-1" />
                    <SearchForm className="my-4 w-full" />
                  </div>
                </header>
                {children}
                <footer className="sticky bottom-0 w-full p-4">
                  <NowPlaying />
                </footer>
              </SidebarInset>
            </LoadingProvider>
          </SidebarProvider>
        </AlertDialogProvider>
      </body>
    </html>
  );
}
